{{- if and .Values.istio.enabled .Values.istio.authorizationPolicy.allowlist.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "app.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "app.name" . }}
  action: ALLOW
  rules:
  - from:
    - source:
        remoteIpBlocks:
          {{- toYaml .Values.istio.authorizationPolicy.allowlist.remoteIpBlocks | nindent 10 }}
{{- end }}
