// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/example/200": {
            "get": {
                "description": "Returns 200 and demonstrates a basic HTTP handler",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "200"
                ],
                "summary": "Example endpoint returning 200",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_internal_api_types.HttpResponse"
                        }
                    }
                }
            }
        },
        "/api/example/200/custom-response": {
            "get": {
                "description": "Returns 200 and demonstrates documenting a custom response with Swagger",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "200"
                ],
                "summary": "Example endpoint returning 200",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_example.customResponseHttpResponse"
                        }
                    }
                }
            }
        },
        "/api/example/200/with/{input}": {
            "get": {
                "description": "Returns 200 and demonstrates path parameter usage",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "200"
                ],
                "summary": "Example endpoint returning 200",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Any input you want",
                        "name": "input",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/app_internal_api_types.HttpResponse"
                        }
                    }
                }
            }
        },
        "/api/example/404": {
            "get": {
                "description": "Returns 404 and demonstrates setting of status code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "404"
                ],
                "summary": "Example endpoint returning 404",
                "responses": {
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/app_internal_api_types.HttpResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app_internal_api_types.HttpResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data contains any logical data to be returned to\nthe client"
                },
                "error": {
                    "description": "Error when set indicates that the response is not\nsuccessful"
                },
                "message": {
                    "description": "Message is an optional message",
                    "type": "string"
                }
            }
        },
        "internal_example.customResponse": {
            "type": "object",
            "properties": {
                "number": {
                    "description": "Number is a numerical property",
                    "type": "integer"
                }
            }
        },
        "internal_example.customResponseHttpResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Data demonstrates defining a customResponse",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_example.customResponse"
                        }
                    ]
                },
                "error": {
                    "description": "Error when set indicates that the response is not\nsuccessful"
                },
                "message": {
                    "description": "Message is an optional message",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Example HTTP API",
	Description:      "This is an API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
