name: app
run-name: ${{ github.actor }} is running pipeline
on: [push]
jobs:
  installation:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install code dependencies
        run: make deps
