name: app
run-name: ${{ github.actor }} is running pipeline
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install system dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Install custom dependencies
        run: make install-swaggo
      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: ./vendor
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: dependencies
      - name: Run tests
        run: make test
    needs: [setup]
  builds:
    runs-on: ubuntu-latest
    steps:
      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: dependencies
      - name: Generate Swagger documentation
        run: |
          go env GOBIN;
          go env GOPATH;
          go env GOROOT;
          export PATH=${PATH}:$(go env GOPATH)/bin;
          make docs-swaggo;
      - name: Verify binary build
        run: make binary
      - name: Verify image build
        run: make image
    needs: [setup]
