name: app
run-name: ${{ github.actor }} is running pipeline
on: [push]
jobs:
  installation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install system dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Install custom dependencies
        run: |
          make install-swaggo
      - name: Generate Swagger documentation
        run: make swaggo-docs
      - name: Run tests
        run: make test
      - name: Verify binary build
        run: make binary
      - name: Verify image build
        run: make image
